import { Controller, Get, Header, Res } from '@nestjs/common';
import type { FastifyReply } from 'fastify';

const page = `<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>VERO · Pedidos</title>
<style>
:root{--ink:#24211e;--muted:#756d65;--paper:#f5f1ea;--card:#fff;--line:#ddd4ca;--red:#a4382d;--green:#37664d;--amber:#9b681e}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font-family:"Segoe UI",Roboto,Arial,Verdana,sans-serif}header{background:#211d19;color:#fff;padding:16px max(20px,calc((100% - 1180px)/2));display:flex;align-items:center;justify-content:space-between;gap:12px}header a{color:#fff;text-decoration:none;font-weight:700}header h1{font-size:22px;margin:0}.wrap{max-width:1180px;margin:24px auto;padding:0 20px}.card{background:var(--card);border:1px solid var(--line);border-radius:16px;padding:20px;box-shadow:0 6px 22px #0000000c}.filters{display:grid;grid-template-columns:1fr 1fr auto;gap:12px;align-items:end;margin-bottom:18px}label{display:block;font-size:13px;font-weight:700;color:#514a44}select,button{width:100%;min-height:44px;margin-top:6px;border-radius:9px;border:1px solid var(--line);padding:10px;font:inherit}button{background:var(--red);color:#fff;border:0;font-weight:750;cursor:pointer}.summary{display:flex;gap:10px;flex-wrap:wrap;margin:14px 0}.pill{border-radius:999px;padding:8px 12px;background:#eee8df;color:var(--muted);font-weight:700}.orders{display:grid;gap:12px}.order{border:1px solid var(--line);border-radius:14px;padding:16px}.order-head{display:flex;justify-content:space-between;gap:12px}.order h2{font-size:18px;margin:0}.meta{color:var(--muted);font-size:13px;margin-top:5px}.money{font-size:20px;font-weight:800}.badge{display:inline-block;border-radius:999px;padding:5px 9px;font-size:12px;font-weight:800}.received{background:#e7eef7;color:#305a8a}.mapped{background:#e4f1e8;color:var(--green)}.pending{background:#f7ead4;color:var(--amber)}.cancelled{background:#f7e3e0;color:var(--red)}.items{margin:14px 0;padding-top:12px;border-top:1px solid #eee6de}.item{display:flex;justify-content:space-between;gap:12px;padding:5px 0}.actions{display:flex;gap:8px;flex-wrap:wrap}.actions button{width:auto;min-height:36px;padding:8px 12px;margin:0;background:#423a34}.empty{padding:30px;text-align:center;color:var(--muted)}.message{margin-bottom:14px;color:var(--muted)}.message.error{color:var(--red)}@media(max-width:700px){header{align-items:flex-start;flex-direction:column}.filters{grid-template-columns:1fr}.order-head{display:block}.money{margin-top:8px}.actions button{flex:1}}
</style></head><body><header><a href="/">← Central VERO</a><h1>Pedidos · Anota AI e iFood</h1><button id="refresh" type="button" style="width:auto;margin:0;background:#423a34">Atualizar</button></header><main class="wrap"><section class="card"><div class="filters"><label>Canal<select id="provider"><option value="">Todos</option><option value="ANOTA_AI">Anota AI</option><option value="IFOOD">iFood</option><option value="VERO_NATIVE">VERO</option></select></label><label>Status<select id="status"><option value="">Todos</option><option value="RECEIVED">Recebido</option><option value="CONFIRMED">Confirmado</option><option value="PREPARING">Em preparo</option><option value="READY">Pronto</option><option value="DISPATCHED">Saiu para entrega</option><option value="COMPLETED">Concluído</option><option value="CANCELLED">Cancelado</option></select></label><button id="apply" type="button">Aplicar filtros</button></div><div id="message" class="message">Carregando pedidos…</div><div id="summary" class="summary"></div><div id="orders" class="orders"></div></section></main>
<script>
const token=()=>localStorage.getItem('vero_token')||'';const tenant=()=>localStorage.getItem('vero_tenant')||'santo-parma';const money=c=>(Number(c||0)/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL',minimumFractionDigits:2});const headers=()=>({'content-type':'application/json','authorization':'Bearer '+token(),'x-tenant-id':tenant()});const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const labels={RECEIVED:'Recebido',CONFIRMED:'Confirmado',PREPARING:'Em preparo',READY:'Pronto',DISPATCHED:'Saiu para entrega',COMPLETED:'Concluído',CANCELLED:'Cancelado'};
async function api(path,options={}){const r=await fetch(path,{...options,headers:{...headers(),...(options.headers||{})},cache:'no-store'});if(!r.ok){let d={};try{d=await r.json()}catch{}throw new Error(d.message||d.code||(r.status===401?'Acesso inválido':'Falha '+r.status));}return r.json()}
function nextActions(o){const map={RECEIVED:[['CONFIRMED','Confirmar'],['CANCELLED','Cancelar']],CONFIRMED:[['PREPARING','Iniciar preparo'],['CANCELLED','Cancelar']],PREPARING:[['READY','Marcar pronto'],['CANCELLED','Cancelar']],READY:[['DISPATCHED','Saiu para entrega'],['COMPLETED','Concluir'],['CANCELLED','Cancelar']],DISPATCHED:[['COMPLETED','Concluir'],['CANCELLED','Cancelar']],COMPLETED:[],CANCELLED:[]};return map[o.status]||[]}
function render(list){document.querySelector('#summary').innerHTML=['ANOTA_AI','IFOOD','VERO_NATIVE'].map(p=>'<span class="pill">'+p.replace('_',' ')+': '+list.filter(o=>o.provider===p).length+'</span>').join('')+'<span class="pill">Pendentes de vínculo: '+list.filter(o=>o.mappingStatus==='PENDING_MAPPING').length+'</span>';const root=document.querySelector('#orders');if(!list.length){root.innerHTML='<div class="empty">Nenhum pedido encontrado.</div>';return}root.innerHTML=list.map(o=>'<article class="order"><div class="order-head"><div><h2>#'+esc(o.reference)+' · '+esc(o.provider.replace('_',' '))+'</h2><div class="meta">'+new Date(o.occurredAt).toLocaleString('pt-BR')+' · '+esc(o.orderType)+' · '+esc(o.customerName||'Cliente não informado')+'</div><div style="margin-top:8px"><span class="badge '+(o.status==='CANCELLED'?'cancelled':'received')+'">'+esc(labels[o.status]||o.status)+'</span> <span class="badge '+(o.mappingStatus==='MAPPED'?'mapped':'pending')+'">'+(o.mappingStatus==='MAPPED'?'Catálogo vinculado':'Mapeamento pendente')+'</span></div></div><div class="money">'+money(o.totalCents)+'</div></div><div class="items">'+o.items.map(i=>'<div class="item"><span>'+i.quantity+'× '+esc(i.name)+(i.mappedProductId?'':' <b>⚠</b>')+'</span><strong>'+money(i.totalCents)+'</strong></div>').join('')+'</div><div class="actions">'+nextActions(o).map(a=>'<button type="button" data-provider="'+esc(o.provider)+'" data-est="'+esc(o.establishmentExternalId)+'" data-id="'+esc(o.externalOrderId)+'" data-status="'+a[0]+'">'+a[1]+'</button>').join('')+'</div></article>').join('')}
async function load(){if(!token()){document.querySelector('#message').textContent='Cadastre a chave na Central VERO antes de acessar pedidos.';document.querySelector('#message').className='message error';return}const q=new URLSearchParams();const p=document.querySelector('#provider').value;const s=document.querySelector('#status').value;if(p)q.set('provider',p);if(s)q.set('status',s);q.set('limit','100');document.querySelector('#message').textContent='Atualizando…';try{const list=await api('/v1/orders?'+q);render(list);document.querySelector('#message').textContent='Pedidos atualizados.';document.querySelector('#message').className='message'}catch(e){document.querySelector('#message').textContent=e.message;document.querySelector('#message').className='message error'}}
document.querySelector('#orders').addEventListener('click',async e=>{const b=e.target.closest('button[data-status]');if(!b)return;b.disabled=true;try{await api('/v1/orders/'+encodeURIComponent(b.dataset.provider)+'/'+encodeURIComponent(b.dataset.est)+'/'+encodeURIComponent(b.dataset.id)+'/status',{method:'PATCH',body:JSON.stringify({status:b.dataset.status})});await load()}catch(err){alert(err.message);b.disabled=false}});document.querySelector('#apply').addEventListener('click',load);document.querySelector('#refresh').addEventListener('click',load);load();
</script></body></html>`;

@Controller()
export class OrdersPageController {
  @Get('pedidos')
  @Header('content-type', 'text/html; charset=utf-8')
  @Header('cache-control', 'no-store, no-cache, must-revalidate, proxy-revalidate')
  page(@Res() reply: FastifyReply): void {
    void reply.send(page);
  }
}
